### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by bulletcoder123** [akash435/Image-Encryption-Decryption#2]
after choosing a file when i try to encrypt i cannot i got this error

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\bulle\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\PROJECT\Image-Encryption-Decryption-main\image_encryption_decryption.py", line 92, in en_fun
    image_input = imread(x, IMREAD_GRAYSCALE)
NameError: name 'imread' is not defined

i cannot decrypt as well

**Comment by bulletcoder123** [comment]
@akash-rajak

**Comment by akash-rajak** [comment]
yes, I will check and write you back

**Comment by akash-rajak** [comment]
OK,

replace this below line of 93 
image_input = imread(x, IMREAD_GRAYSCALE)

with 
image_input = cv2.imread(x, IMREAD_GRAYSCALE)



and then try to run and check

thank you

**Comment by bulletcoder123** [comment]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\bulle\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\PROJECT\Image-Encryption-Decryption-main\image_encryption_decryption.py", line 92, in en_fun
    image_input = cv2.imread(x, IMREAD_GRAYSCALE)
NameError: name 'IMREAD_GRAYSCALE' is not defined




i am still getting this error 
And also, while decryption also i got this error


Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\bulle\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "D:\PROJECT\Image-Encryption-Decryption-main\image_encryption_decryption.py", line 112, in de_fun
    image_output = image_encrypted * key
NameError: name 'image_encrypted' is not defined

please help by today.....i need it urgently if possible thank you

**Comment by bulletcoder123** [comment]
@akash-rajak

**Comment by akash-rajak** [comment]
yes

**Comment by akash-rajak** [comment]
@bulletcoder123 
check the code, i updated just now, try to run the updated code

**Comment by bulletcoder123** [comment]
@akash-rajak  thank you so much bro ...... i will remember you for lifetime ....its a big relief

**Comment by akash-rajak** [comment]
you are welcome
